let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

syntax on

call plug#begin()
Plug 'altercation/vim-colors-solarized'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'mattn/emmet-vim'
Plug 'preservim/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'vim-ruby/vim-ruby'
Plug 'vim-test/vim-test'
call plug#end()

set background=light
colorscheme solarized

" Set NERDTree to appear on the right side
let g:NERDTreeWinPos = "right"

let mapleader = "\<space>"

" nnoremap <leader>l :NERDTreeToggle<CR>
nmap <leader>o :NERDTreeToggle<CR>

" Remap buffer navigation
nmap <leader>bs :buffers<cr>
nmap <leader>b :buffer
nmap <leader>bn :bnext<cr>
nmap <leader>bp :bprevious<cr>
nmap <leader>bd :bdelete

" Easily suspend vim so that the terminal can be accessed quickly. Return to
" vim by pressing 'fg'
nmap <leader>z :suspend<cr>

" Edit your vimrc in a new tab. Type space, v, r in sequence to trigger
nmap <leader>vrc :tabe $MYVIMRC<cr>

" Source (reload) your vimrc. Type space, s, o in sequence to trigger
nmap <leader>so :source $MYVIMRC<cr>

" Opens a new vertical split
nmap <leader>nv <C-w>v

" Opens a new horizontal split
nmap <leader>ns <C-w>s

" Closes a window
nmap <leader>cw <C-w>c

" Makes the current window the only one on screen and closes other windows
nmap <leader>co <C-w>o

" Go into window navigation/management mode. Type space, w to trigger
nmap <leader>w <C-w>

" Make current window be a vertical split
nmap <leader>wv <C-w>H

" Make current window be a horizontal. 's' is used as a sideways nmemonic and
" because '<leader>wh' is already used for moving cursor between windows
nmap <leader>ws <C-w>K

" Move cursor up or down respectively in chunks. Type space, u or space, d to
" trigger
nmap <leader>u <C-u>
nmap <leader>d <C-d>

" Remap crtl-p to use leader key and f
" nmap <leader>f <C-p>

" Remap file finding for fzf
nnoremap <silent> <leader>f :Files<CR>

" Remap code comment command
nmap <leader>/ gcc

" Open Rails schema.rb file in new tab
nmap <leader>sc :tabe db/schema.rb<cr>

" Open Rails config/routes.rb file in new tab
nmap <leader>ro :tabe config/routes.rb<cr>

" Test runner mappings
nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>tf :TestFile<CR>
nmap <silent> <leader>ta :TestSuite<CR>
nmap <silent> <leader>tl :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>

nmap <leader>c :Econtroller<cr>
nmap <leader>m :Emodel<cr>
nmap <leader>v :Eview<cr>

set relativenumber number
set t_Co=256
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
set nocompatible
filetype plugin on
set hidden
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set incsearch
nnoremap <leader>cc :set colorcolumn=100<cr>
nnoremap <leader>ncc :set colorcolumn-=100<cr>
set rtp+=/opt/homebrew/opt/fzf
set grepprg=rg\ --vimgrep\ --smart-case\ --follow
