let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

syntax on

call plug#begin()
Plug 'ashfinal/vim-colors-violet'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'morhetz/gruvbox'
Plug 'pineapplegiant/spaceduck', { 'branch': 'main' }
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vividchalk'
Plug 'vim-test/vim-test'
call plug#end()

" gruvbox config
" set bg=dark
" let g:gruvbox_contrast_dark = 'hard'
" autocmd vimenter * ++nested colorscheme gruvbox

" spacecamp config
" colorscheme spacecamp

" spaceduck config
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
colorscheme spaceduck

" violet config
" set bg=light
" colorscheme violet

" vividchalk config
" set bg=dark
" colorscheme vividchalk

" Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'

" ag is fast enough that CtrlP doesn't need to cache
let g:ctrlp_use_caching = 0

let mapleader = "\<space>"

" Edit your vimrc in a new tab. Type space, v, r in sequence to trigger
nmap <leader>vrc :tabe $MYVIMRC<cr>

" Source (reload) your vimrc. Type space, s, o in sequence to trigger
nmap <leader>so :source $MYVIMRC<cr>

" Go into window navigation/management mode. Type space, w to trigger
nmap <leader>w <C-w>

" Make current window be a vertical split
nmap <leader>wv <C-w>H

" Make current window be a horizontal. 's' is used as a sideways nmemonic and
" because '<leader>wh' is already used for moving cursor between windows
nmap <leader>ws <C-w>K

" Move cursor up or down respectively in chunks. Type space, u or space, d to
" trigger
nmap <leader>u <C-u>
nmap <leader>d <C-d>

" Remap crtl-p to use leader key and f
nmap <leader>f <C-p>

" Open Rails schema.rb file in new tab
nmap <leader>sc :tabe db/schema.rb<cr>

" Remap ctrl o which goes to previous location. Handy for going up a directory
nmap <leader>a <C-o>

" Test runner mappings
nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>tf :TestFile<CR>
nmap <silent> <leader>ta :TestSuite<CR>
nmap <silent> <leader>tl :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>

set relativenumber number
set t_Co=256
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
set nocompatible
set hidden
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set incsearch
" set colorcolumn=80
