# Enable Vim mode in zsh
bindkey -v

# Setup tab completion
autoload -Uz compinit && compinit

# Set Vim as editor of choice
export EDITOR=vim

. /usr/local/opt/asdf/libexec/asdf.sh

#########################
##### PROMPT CONFIG #####
#########################
autoload -Uz vcs_info
zstyle ':vcs_info:git*' formats '%K{green}%F{black} %b %f%k'
precmd() { vcs_info }

setopt PROMPT_SUBST
PROMPT='%K{blue}%F{black} ${PWD/#$HOME/~} %f%k%K{green}%F{blue}'$'\ue0b0%f%k${vcs_info_msg_0_}%F{green}'$'\ue0b0%f '

###################
##### Aliases #####
###################

# Bundler related aliases
alias bex="bundle exec"
alias bi="bundle install"

# Dir navigation aliases
alias cdc="cd ~/code"
alias cdw="cd ~/code/work"
alias cddf="cd ~/code/dotfiles"

# Git related aliases
alias ga="git add"
alias gb="git branch"
alias gbd="git branch -D"
alias gbn="git checkout -b"
alias gc="git commit -m"
alias gco="git checkout"
alias gd="git diff"
alias gfix="vim -p +/HEAD \$(git diff --name-only | uniq)"
alias gl="git log"
alias gr="git remote -v"
alias gs="git status"

# Rails related aliases
alias bd="bin/dev"
alias br="bin/rails"
alias rc="bin/rails console"
alias rcl="bin/rails tmp:clear && bin/rails log:clear"
alias rcs="bin/rails console -s"
alias rdbc="bin/rails dbconsole"
alias rdbfl="bin/rails db:fixtures:load"
alias rdbm="bin/rails db:migrate"
alias rdbms="bin/rails db:migrate:status"
alias rdbrb="bin/rails db:rollback"
alias rdbs="bin/rails db:seed"
alias rg="bin/rails g"
alias rgcon="bin/rails g controller"
alias rgit="bin/rails g integration_test"
alias rgjob="bin/rails g job"
alias rgmod="bin/rails g model"
alias rgmail="bin/rails g mailer"
alias rgmig="bin/rails g migration"
alias rgres="bin/rails g resource"
alias rgscaf="bin/rails g scaffold"
alias rgstim="bin/rails g stimulus"
alias rr="bin/rails routes -g"
alias rs="bin/rails server"
alias rt="bin/rails test"
alias rta="bin/rails test:all"
alias rtc="bin/rails test:controllers"
alias rti="bin/rails test:integration"
alias rtm="bin/rails test:models"
alias rts="bin/rails test:system"

# Redis related aliases
alias reds="redis-server"

# Standard related aliases
alias sf="standardrb --fix"

# Yarn related aliases
alias yi="yarn install"

#####################
##### Functions #####
#####################

# Git related functions
gac () {
  if [[ $# > 1 ]]; then
    git add $1 && git commit -m $2
  else
    git add . && git commit -m $1
  fi
}

gf () {
  if [[ $# > 1 ]]; then
    git fetch $@
  else
    git fetch origin $1
  fi
}

gp () {
  CURRENT_BRANCH=$(git branch --show-current)
  if [[ $1 ]]; then
    git push $1 ${CURRENT_BRANCH}
  else
    git push origin ${CURRENT_BRANCH}
  fi
}

gpl () {
  if [[ $# > 1 ]]; then
    git pull $@
  else
    git pull origin $1
  fi
}

# Vim related functions
v () {
  if [[ $# == 1 ]]; then
    vim $1
  elif [[ $# > 1 ]]; then
    vim -O $@
  else
    vim .
  fi
}

